### ISSUE TITLE
兼容linux

### ISSUE THREAD

**Issue by gouchaoer** [jilieryuyi/wing-process#1]
能有人出来做windows的进程管理真的很惊喜，毕竟php的跨平台兼容很难得
symfony的process组件、swoole的create_process和原生的pcntl都有各种问题，一个兼容linux/win的扩展会很棒

**Comment by gouchaoer** [comment]
symfony的process组件兼容win/linux，不过win下有一些小问题

**Comment by jilieryuyi** [comment]
嗯，由于实现方式完全不一样，很难兼容，现在能想到的能兼容的方式是cygwin，不过这个开发成本相对比较高了

**Comment by jilieryuyi** [comment]
mac分支已经部分支持mac和linux方向下的守护进程支持，不久的将来，能完全兼容linux、mac和windows！！

**Comment by gouchaoer** [comment]
awesome

**Comment by jilieryuyi** [comment]
完全兼容linux、mac和windows的版本2.0.0已发布！
